/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package todo_manager;

import database.DB;
import helper.ENUMS;
import java.awt.Color;
import static java.lang.Thread.sleep;
import javax.swing.JOptionPane;
import schema.User;

/**
 *
 * @author user
 */
public class Signup extends javax.swing.JFrame {

    public Signup() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        enter_name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        enter_pass = new javax.swing.JPasswordField();
        signup_btn = new javax.swing.JButton();
        goto_signin = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        enter_email = new javax.swing.JTextField();
        error_label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Signup");
        setLocation(new java.awt.Point(0, 0));
        setLocationByPlatform(true);
        setName("signup"); // NOI18N
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(27, 20, 69));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/todo_manager/u-todo.png"))); // NOI18N
        jLabel1.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(27, 20, 69));
        jLabel2.setText("Name");

        enter_name.setFont(new java.awt.Font("Fira Code", 1, 14)); // NOI18N
        enter_name.setForeground(new java.awt.Color(27, 20, 69));
        enter_name.setToolTipText("Name");
        enter_name.setCaretColor(java.awt.Color.white);

        jLabel3.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(27, 20, 69));
        jLabel3.setText("Password");

        signup_btn.setBackground(new java.awt.Color(50, 224, 109));
        signup_btn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        signup_btn.setForeground(new java.awt.Color(27, 20, 69));
        signup_btn.setText("Signup");
        signup_btn.setBorder(null);
        signup_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signup_btn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        signup_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onSingup(evt);
            }
        });

        goto_signin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        goto_signin.setForeground(new java.awt.Color(27, 20, 69));
        goto_signin.setText("Have an account?");
        goto_signin.setBorder(null);
        goto_signin.setBorderPainted(false);
        goto_signin.setContentAreaFilled(false);
        goto_signin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        goto_signin.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        goto_signin.setFocusPainted(false);
        goto_signin.setIconTextGap(0);
        goto_signin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onGotoSignin(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(27, 20, 69));
        jLabel4.setText("E-mail");

        enter_email.setFont(new java.awt.Font("Fira Code", 1, 14)); // NOI18N
        enter_email.setForeground(new java.awt.Color(27, 20, 69));
        enter_email.setToolTipText("e-mail");
        enter_email.setCaretColor(java.awt.Color.white);

        error_label.setFont(new java.awt.Font("Montserrat Medium", 3, 12)); // NOI18N
        error_label.setForeground(new java.awt.Color(255, 0, 0));
        error_label.setText("*");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(enter_pass)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(enter_name, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addComponent(enter_email, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(goto_signin)
                            .addComponent(signup_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(error_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enter_name, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enter_email, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enter_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(error_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(signup_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(goto_signin)
                .addGap(99, 99, 99))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void onSingup(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onSingup
        String user_email = enter_email.getText().trim();
        String user_password = new String(enter_pass.getPassword()).trim();
        String user_name = enter_name.getText().trim();

        String q_s = "SELECT * FROM " + ENUMS.TABLE.users + " WHERE email='" + user_email.trim() + "';";
        try {
            if (!user_email.matches("^\\w+([\\.-]?\\w+)*@\\w+([\\.-]?\\w+)*(\\.\\w{2,3})+$")) {
                JOptionPane.showMessageDialog(rootPane, "Not Valid Email");
                throw new Exception("Not valid email.");
            }            DB db = new DB(q_s);
            while (db.result.next()) {
                if (!db.result.wasNull()) {
                    error_label.setText("This email is already in use.");
                    //throw new Exception("This email is already in use.");
                }
            }
            db.closeDB();
            if (user_email.length() < 3) {
                error_label.setText("Email is invalid.");
                throw new Exception("Entered e-mail is invalid.");
            } else if (user_password.length() < 6) {
                String error = "Password length should be minimum 6.";
                error_label.setText(error);
                throw new Exception(error);
            } else if (user_name.length() < 3) {
                String error = "User name is too short.";
                error_label.setText(error);
                throw new Exception(error);
            } else {
                error_label.setText("");
            }
            String insert_str = "INSERT INTO " + ENUMS.TABLE.users + " (name, email, password) VALUES ('" + user_name.trim() + "','" + user_email.trim() + "','" + user_password.trim() + "');";
            DB insert_db = new DB(insert_str);
            System.out.println(insert_db.isSuccess);
            enter_email.setText("");
            enter_pass.setText("");
            enter_name.setText("");
            error_label.setForeground(Color.GREEN);
            error_label.setText("Redirecting to Home screen.");

            insert_db.closeDB();

            if (insert_db.isSuccess > 0) {
                //re-fatch user data from database.
                DB res = new DB(q_s);
                while (res.result.next()) {
                    int id = res.result.getInt("id");
                    String name = res.result.getString("name");
                    System.out.println(name);
                    String email = res.result.getString("email");
                    System.out.println(id);
                    this.setVisible(false);
                    new Home(new User(id, name, email)).setVisible(true);
                }
                res.closeDB();
            } else {
                throw new Exception("Failed to sign up.");
            }
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
            javax.swing.JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_onSingup

    private void onGotoSignin(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onGotoSignin
        // TODO add your handling code here:
        new Login().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_onGotoSignin

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Signup signup = new Signup();
                signup.setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JTextField enter_email;
    javax.swing.JTextField enter_name;
    private javax.swing.JPasswordField enter_pass;
    private javax.swing.JLabel error_label;
    private javax.swing.JButton goto_signin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton signup_btn;
    // End of variables declaration//GEN-END:variables
}
